export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type ModelRow = {
  id: string;
  slug: string;
  name: string;
  developer: string | null;
  institution: string | null;
  family: string | null;
  type: string | null;
  primary_task: string | null;
  status: string | null;
  vendor_api_status: string | null;
  deployment: Json;
  release_date: string | null;
  previous_version: string | null;
  tier: string | null;
  logo: string | null;
  images: Json;
  tags: Json;
  links: Json;
  sources: Json;
  pricing: Json;
  parameters: string | null;
  active_parameters: string | null;
  context_window: string | null;
  benchmarks: Json;
  capabilities: Json;
  field_confidence: Json;
  featured: boolean | null;
  boost: number | null;
  verified: boolean | null;
  verification_status: string | null;
  needs_review: boolean | null;
  curator_notes: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  source: string | null;
  modality: Json;
  license: string | null;
  base_model: string | null;
  is_legacy_curated: boolean | null;
  cost_tiers: Json | null;
  pricing_last_verified: string | null;
  metadata: Json;
  quality_status: string | null;
  quality_score: number | null;
  quality_breakdown: Json;
  quality_reasons: Json;
  quality_checked_at: string | null;
  card_summary: string | null;
  page_overview: string | null;
  editorial_note: string | null;
  description: string | null;
  description_draft: string | null;
  key_features: Json;
  key_features_draft: Json;
  chatgpt_availability: boolean | null;
  api_availability: Json;
  aliases: Json;
  staged_changes: Json;
  staged_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ModelInsert = {
  id?: string;
  slug: string;
  name: string;
  developer?: string | null;
  institution?: string | null;
  family?: string | null;
  type?: string | null;
  primary_task?: string | null;
  status?: string | null;
  vendor_api_status?: string | null;
  deployment?: Json;
  release_date?: string | null;
  previous_version?: string | null;
  tier?: string | null;
  logo?: string | null;
  images?: Json;
  tags?: Json;
  links?: Json;
  sources?: Json;
  pricing?: Json;
  parameters?: string | null;
  active_parameters?: string | null;
  context_window?: string | null;
  benchmarks?: Json;
  capabilities?: Json;
  field_confidence?: Json;
  featured?: boolean | null;
  boost?: number | null;
  verified?: boolean | null;
  verification_status?: string | null;
  needs_review?: boolean | null;
  curator_notes?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  source?: string | null;
  modality?: Json;
  license?: string | null;
  base_model?: string | null;
  is_legacy_curated?: boolean | null;
  cost_tiers?: Json | null;
  pricing_last_verified?: string | null;
  metadata?: Json;
  quality_status?: string | null;
  quality_score?: number | null;
  quality_breakdown?: Json;
  quality_reasons?: Json;
  quality_checked_at?: string | null;
  card_summary?: string | null;
  page_overview?: string | null;
  editorial_note?: string | null;
  description?: string | null;
  description_draft?: string | null;
  key_features?: Json;
  key_features_draft?: Json;
  chatgpt_availability?: boolean | null;
  api_availability?: Json;
  aliases?: Json;
  staged_changes?: Json;
  staged_at?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type ModelUpdate = {
  id?: string;
  slug?: string;
  name?: string;
  developer?: string | null;
  institution?: string | null;
  family?: string | null;
  type?: string | null;
  primary_task?: string | null;
  status?: string | null;
  vendor_api_status?: string | null;
  deployment?: Json;
  release_date?: string | null;
  previous_version?: string | null;
  tier?: string | null;
  logo?: string | null;
  images?: Json;
  tags?: Json;
  links?: Json;
  sources?: Json;
  pricing?: Json;
  parameters?: string | null;
  active_parameters?: string | null;
  context_window?: string | null;
  benchmarks?: Json;
  capabilities?: Json;
  field_confidence?: Json;
  featured?: boolean | null;
  boost?: number | null;
  verified?: boolean | null;
  verification_status?: string | null;
  needs_review?: boolean | null;
  curator_notes?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  source?: string | null;
  modality?: Json;
  license?: string | null;
  base_model?: string | null;
  is_legacy_curated?: boolean | null;
  cost_tiers?: Json | null;
  pricing_last_verified?: string | null;
  metadata?: Json;
  quality_status?: string | null;
  quality_score?: number | null;
  quality_breakdown?: Json;
  quality_reasons?: Json;
  quality_checked_at?: string | null;
  card_summary?: string | null;
  page_overview?: string | null;
  editorial_note?: string | null;
  description?: string | null;
  description_draft?: string | null;
  key_features?: Json;
  key_features_draft?: Json;
  chatgpt_availability?: boolean | null;
  api_availability?: Json;
  aliases?: Json;
  staged_changes?: Json;
  staged_at?: string | null;
  created_at?: string;
  updated_at?: string;
};
