import type { Json } from './models';

export type NewsItemRow = {
  id: string;
  slug: string;
  title: string;
  body: string;
  excerpt: string | null;
  cover_image: string | null;
  author: string | null;
  category: string | null;
  publish_date: string | null;
  read_time: string | null;
  status: string | null;
  confidence_level: string | null;
  external_sources: Json;
  sources: Json;
  related_models: Json;
  tags: Json;
  article_type: string | null;
  deep_dive_score: number | null;
  read_time_minutes: number | null;
  has_diagram: boolean | null;
  mermaid_diagrams: Json;
  curator_reviewed: boolean | null;
  breakthrough_signals: Json;
  quality_status: string | null;
  quality_score: number | null;
  quality_reasons: Json;
  quality_checked_at: string | null;
  created_at: string;
  updated_at: string;
};

export type NewsItemInsert = {
  id?: string;
  slug: string;
  title: string;
  body: string;
  excerpt?: string | null;
  cover_image?: string | null;
  author?: string | null;
  category?: string | null;
  publish_date?: string | null;
  read_time?: string | null;
  status?: string | null;
  confidence_level?: string | null;
  external_sources?: Json;
  sources?: Json;
  related_models?: Json;
  tags?: Json;
  article_type?: string | null;
  deep_dive_score?: number | null;
  read_time_minutes?: number | null;
  has_diagram?: boolean | null;
  mermaid_diagrams?: Json;
  curator_reviewed?: boolean | null;
  breakthrough_signals?: Json;
  quality_status?: string | null;
  quality_score?: number | null;
  quality_reasons?: Json;
  quality_checked_at?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type NewsItemUpdate = {
  id?: string;
  slug?: string;
  title?: string;
  body?: string;
  excerpt?: string | null;
  cover_image?: string | null;
  author?: string | null;
  category?: string | null;
  publish_date?: string | null;
  read_time?: string | null;
  status?: string | null;
  confidence_level?: string | null;
  external_sources?: Json;
  sources?: Json;
  related_models?: Json;
  tags?: Json;
  article_type?: string | null;
  deep_dive_score?: number | null;
  read_time_minutes?: number | null;
  has_diagram?: boolean | null;
  mermaid_diagrams?: Json;
  curator_reviewed?: boolean | null;
  breakthrough_signals?: Json;
  quality_status?: string | null;
  quality_score?: number | null;
  quality_reasons?: Json;
  quality_checked_at?: string | null;
  created_at?: string;
  updated_at?: string;
};
